# __Первый проект__
server {
	listen 80;
	server_name project1.local www.project1.local;
	return 301 https://$host$request_uri; # 301 именно принудительно
} # Принудительное перенаправление HTTP на HTTPS

server {
	# Работа по HTTPS 443 с сертификатом
	listen 443 ssl;
	server_name project1.local www.project1.local;
	
	ssl_certificate /etc/nginx/ssl/server.pem; # Публичный сертификат
	ssl_certificate_key /etc/nginx/ssl/server.key; # Приватный ключ
	
	ssl_protocols TLSv1.2 TLSv1.3;
    	ssl_ciphers HIGH:!aNULL:!MD5;
    	ssl_prefer_server_ciphers on;
    	
    	root /var/www/project1;
    	index index.html index.htm;
    	
    	location /common/ {
	    alias /var/www/shared/common/;
	    expires 7d;  # Кэшировать на 7 дней
	    add_header Cache-Control "public";
	}
    	
    	location / {
    		try_files $uri $uri/ =404;
    	}
    	
    	access_log /var/log/nginx/project1_access.log;
    	error_log /var/log/nginx/project1_error.log;
}
# __Второй проект__
server {
	listen 80;
	server_name project2.local www.project2.local;

	# Принудительное перенаправление HTTP на HTTPS 
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	server_name project2.local www.project2.local;

	ssl_certificate /etc/nginx/ssl/server.pem;
	ssl_certificate_key /etc/nginx/ssl/server.key;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers HIGH:!aNULL:!MD5;
	ssl_prefer_server_ciphers on;

	root /var/www/project2;
	index index.html index.htm;

	location /common/ {
	    alias /var/www/shared/common/;
	    expires 7d;  # Кэшировать на 7 дней
	    add_header Cache-Control "public";
	}
	
	location / {
        	try_files $uri $uri/ =404;
    	}
    
	# Логи
	access_log /var/log/nginx/project2_access.log;
	error_log /var/log/nginx/project2_error.log;
}
